# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdrevenueTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AppsFlyer-AdRevenue'

  target 'AdrevenueTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AdrevenueTestAppUITests' do
    # Pods for testing
  end

end
